# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects JC Ansible role.
#
# The Webarchitects JC Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects JC Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JC Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install Bash completion
  block:

    - name: Generate Bash completion script
      ansible.builtin.shell: |
        set -e -o pipefail
        jc -B > /root/jc_bash_completion
      changed_when: false
      args:
        executable: "{{ ansible_local.bash.path | default('/bin/bash') }}"

    - name: Bash completion directory present
      ansible.builtin.file:
        path: /etc/bash_completion.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Stat /root/jc_bash_completion
      ansible.builtin.stat:
        path: /root/jc_bash_completion
      register: jc_bash_completion_proposed

    - name: Debug jc_bash_completion_proposed
      ansible.builtin.debug:
        var: jc_bash_completion_proposed
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: Stat /root/jc_bash_completion
      ansible.builtin.stat:
        path: /etc/bash_completion.d/jc
      register: jc_bash_completion_existing

    - name: Debug jc_bash_completion_existing
      ansible.builtin.debug:
        var: jc_bash_completion_existing
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: Bash completion script in place
      ansible.builtin.copy:
        src: /root/jc_bash_completion
        dest: /etc/bash_completion.d/jc
        remote_src: true
        owner: root
        group: root
        mode: "0644"
        validate: bash %s
      when:
        - jc_bash_completion_proposed.stat.exists | bool
        - ( not jc_bash_completion_existing.stat.exists | bool ) or ( jc_bash_completion_proposed.stat.checksum != jc_bash_completion_existing.stat.checksum )

  when: jc_bash | bool
  tags:
    - jc
...
