# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects JC Ansible role.
#
# The Webarchitects JC Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects JC Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JC Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install or upgrade jc using a deb
  block:

    - name: Uninstall pipx version if present
      community.general.pipx:
        name: jc
        state: absent
        executable: /usr/bin/pipx
      when:
        - jc_pipx is defined
        - jc_pipx | bool

    - name: Download jc deb
      ansible.builtin.get_url:
        url: "https://github.com/kellyjonbrazil/jc/releases/download/v{{ jc_proposed }}/jc_{{ jc_proposed }}-1_{{ ansible_local.dpkg.arch }}.deb"
        dest: "/root/jc_{{ jc_proposed }}-1_{{ ansible_local.dpkg.arch }}.deb"
        mode: "0600"
        owner: root
        group: root

    - name: Install jc deb
      ansible.builtin.apt:
        deb: "/root/jc_{{ jc_proposed }}-1_{{ ansible_local.dpkg.arch }}.deb"
        state: present
        force: true
        autoclean: true
        autoremove: true
      when: not ansible_check_mode | bool

  tags:
    - jc
...
