---
- name: Install or upgrade jc using a deb
  block:

    - name: Uninstall pip3 version if present
      ansible.builtin.pip:
        name: jc
        state: absent
        executable: /usr/bin/pip3

    - name: Download jc deb
      ansible.builtin.get_url:
        url: "https://github.com/kellyjonbrazil/jc/releases/download/v{{ jc_proposed }}/jc_{{ jc_proposed }}-1_amd64.deb"
        dest: "/root/jc_{{ jc_proposed }}-1_amd64.deb"
        mode: 0600
        owner: root
        group: root

    - name: Install jc deb
      ansible.builtin.apt:
        deb: "/root/jc_{{ jc_proposed }}-1_amd64.deb"
        state: present
        force: true
        autoclean: true
        autoremove: true

  tags:
    - jc
...
