---
- name: Install or upgrade jc using pip
  block:

    - name: Uninstall jc deb if present
      ansible.builtin.apt:
        pkg:
          - jc
        state: absent
      when: ( jc_deb is defined ) and ( jc_deb )

    - name: jc git repo present
      ansible.builtin.git:
        repo: https://github.com/kellyjonbrazil/jc.git
        dest: /usr/local/src/jc
        version: "{{ jc_version }}"
        clone: true
        force: true
        update: true

    - name: Install jc branch using git
      ansible.builtin.pip:
        name: file:///usr/local/src/jc
        requirements: /usr/local/src/jc/requirements.txt
        state: forcereinstall
        executable: /usr/bin/pip3

  tags:
    - jc
...
