---
- name: Install or upgrade jc using pip
  block:

    - name: Uninstall jc deb if present
      ansible.builtin.apt:
        pkg:
          - jc
        state: absent
      when:
        - ( jc_deb is defined ) and ( jc_deb | bool )
        - ( ansible_effective_user_id == 0 )

    - name: jc git repo present
      ansible.builtin.git:
        repo: https://github.com/kellyjonbrazil/jc.git
        dest: "{{ jc_src }}/jc"
        version: "{{ jc_version }}"
        clone: true
        force: true
        update: true

    - name: Install jc requirements using pip3 from git repo
      ansible.builtin.pip:
        requirements: "{{ jc_src }}/jc/requirements.txt"
        state: forcereinstall
        executable: /usr/bin/pip3

    - name: Install jc using pip3 from git repo
      ansible.builtin.pip:
        name: "file://{{ jc_src }}/jc"
        state: forcereinstall
        executable: /usr/bin/pip3

  tags:
    - jc
...
