# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects JC Ansible role.
#
# The Webarchitects JC Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects JC Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects JC Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Install or upgrade jc using pipx
  block:

    - name: Uninstall jc deb if present
      ansible.builtin.apt:
        pkg:
          - jc
        state: absent
      when:
        - ( jc_deb is defined ) and ( jc_deb | bool )
        - ( ansible_effective_user_id == 0 )

    - name: Debig jc_pipx variable
      ansible.builtin.debug:
        var: jc_pipx
      when: jc_pipx is defined

    - name: Install jc using pipx from git repo
      community.general.pipx:
        name: jc
        source: "git+https://github.com/kellyjonbrazil/jc.git@{{ jc_version }}"
        executable: /usr/bin/pipx
      when: ( jc_pipx is not defined ) or ( not jc_pipx | bool )

    - name: Reinstall jc using pipx from git repo
      community.general.pipx:
        name: jc
        source: "git+https://github.com/kellyjonbrazil/jc.git@{{ jc_version }}"
        state: reinstall
        executable: /usr/bin/pipx
      when:
        - jc_pipx is defined
        - jc_pipx | bool

  tags:
    - jc
...
