---
- name: Install or upgrade jc
  block:

    - name: Check version variable for deb and pip installs
      ansible.builtin.assert:
        that:
          - ( jc_version is regex('^[0-9.]{5,10}$') ) or ( jc_version == "latest" )
      when: jc_install is regex('^deb|pip$')

    - name: Check branch variable for git installs
      ansible.builtin.assert:
        that:
          - jc_version is regex('^dev|master$')
      when: jc_install == "git"

    - name: Fail if a deb install is specified and the role is not being run as root
      ansible.builtin.fail:
        msg: "This role can be run without become / as a non-root user for git and pip installs but not for deb installs"
      when:
        - jc_install == "deb"
        - ansible_effective_user_id != 0

    - name: Packages pip3 and jc present
      ansible.builtin.apt:
        pkg:
          - jc
          - python3-pip
        state: present
      when: ansible_effective_user_id == 0

    - name: Check that pip3 is present
      ansible.builtin.command: which pip3
      check_mode: false
      changed_when: false

    - name: Which jc
      ansible.builtin.command: which jc
      check_mode: false
      changed_when: false
      register: jc_which
      failed_when: jc_which.rc is not regex('^0|1$')

    - name: Check the installed jc version
      ansible.builtin.include_tasks: version.yml
      when: jc_which.rc == 0

    - name: Find the latest version of jc
      block:

        - name: Use a HEAD request to get the latest redirect URL
          ansible.builtin.uri:
            url: https://github.com/kellyjonbrazil/jc/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: jc_latest_headers

        - name: Set a fact for the latest version of jc
          ansible.builtin.set_fact:
            jc_proposed: "{{ jc_latest_headers.location | urlsplit('path') | basename | regex_replace('^v') | string }}"

      when: jc_version == "latest"

    - name: Set a fact for the proposed version of jc for deb and pip installs
      ansible.builtin.set_fact:
        jc_proposed: "{{ jc_version | string }}"
      when: jc_proposed is not defined

    - name: Debug the proposed version and variable type
      ansible.builtin.debug:
        msg:
          - "jc_proposed variable value {{ jc_proposed }}"
          - "jc_proposed variable type {{ jc_proposed | type_debug }}"
        verbosity: 2

    - name: Debug install task to be run
      ansible.builtin.debug:
        msg: "jc is to be installed using {{ jc_install }} version {{ jc_proposed }}"
        verbosity: 2

    - name: Include deb install tasks
      ansible.builtin.include_tasks: deb.yml
      when:
        - jc_install == "deb"
        - ( jc_deb is not defined ) or ( jc_existing is not defined ) or ( ( jc_version == "latest" ) and ( jc_existing is version(jc_proposed, '<') ) ) or ( ( jc_version != "latest" ) and ( jc_existing is not version(jc_version, '=') ) )
        - ansible_effective_user_id == 0

    - name: Include git install tasks
      ansible.builtin.include_tasks: git.yml
      when:
        - jc_install == "git"

    - name: Debug pip variables
      ansible.builtin.debug:
        msg:
          - "jc_pip variable value {{ jc_pip }}"
          - "jc_existing variable value {{ jc_existing }}"
          - "jc_proposed variable value {{ jc_proposed }}"
        verbosity: 2
      when: jc_pip is defined

    - name: Include pip install tasks
      ansible.builtin.include_tasks: pip.yml
      when:
        - jc_install == "pip"
        - ( jc_pip is not defined ) or ( jc_pip is defined and jc_pip | bool and jc_existing is defined and jc_existing is version(jc_proposed, '<') )

    - name: Which jc
      ansible.builtin.command: which jc
      check_mode: false
      changed_when: false
      register: jc_which
      failed_when: jc_which.rc is not regex('^0|1$')

    - name: Something has gone wrong
      ansible.builtin.fail:
        msg: "Sorry, something has gone wrong, jc is not present"
      when: jc_which.rc != 0
      check_mode: true

    - name: Check the installed jc version
      ansible.builtin.include_tasks: version.yml
      when: jc_which.rc == 0

    - name: Install Bash completion
      ansible.builtin.include_tasks: bash.yml
      when:
        - ( jc_bash is defined ) and ( jc_bash | bool )
        - ( jc_existing is defined ) and ( jc_existing is version('1.20.1', '>=') )
        - ( jc_install != "deb" ) or ( jc_install == "deb" and jc_existing is version('1.20.2', '<') )
        - ansible_effective_user_id == 0

    - name: The installed version of jc
      ansible.builtin.debug:
        msg: "jc version {{ jc_existing }} is installed"

  when: jc | bool
  tags:
    - jc
...
