---
- name: Install or upgrade jc using pip
  block:

    - name: Uninstall jc deb if present
      ansible.builtin.apt:
        pkg:
          - jc
        state: absent
      when: ( jc_deb is defined ) and ( jc_deb | bool )

    - name: pip3 present
      apt:
        pkg:
          - python3-pip
        state: present

    - name: Install jc using pip3
      ansible.builtin.pip:
        name: "jc=={{ jc_proposed }}"
        state: forcereinstall
        executable: /usr/bin/pip3

  tags:
    - jc
...
