---
- name: Install or upgrade jc using pip
  block:

    - name: Uninstall jc deb if present
      ansible.builtin.apt:
        pkg:
          - jc
        state: absent
      when:
        - ( jc_deb is defined ) and ( jc_deb | bool )
        - ( ansible_effective_user_id == 0 )

    - name: Install jc using pip3
      ansible.builtin.pip:
        name: "jc=={{ jc_proposed }}"
        state: forcereinstall
        executable: /usr/bin/pip3

  tags:
    - jc
...
