---
- name: Check the version of jc
  block:

    - name: Check the jc version
      ansible.builtin.command: jc -a
      check_mode: false
      changed_when: false
      register: jc_a

    - name: Set a fact for the existing version information
      ansible.builtin.set_fact:
        jc_existing_json: "{{ jc_a.stdout | from_json }}"

    - name: Set a fact for the existing version information
      ansible.builtin.set_fact:
        jc_existing: "{{ jc_existing_json.version | string }}"

    - name: Debug the existing version and variable type
      ansible.builtin.debug:
        msg:
          - "variable value {{ jc_existing }}"
          - "variable type {{ jc_existing | type_debug }}"
        verbosity: 2

  tags:
    - jc
...
